//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadrigalDev_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class madrigaldev_testEntities : DbContext
    {
        public madrigaldev_testEntities()
            : base("name=madrigaldev_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_empresa> t_empresa { get; set; }
        public DbSet<t_login> t_login { get; set; }
        public DbSet<t_usuario> t_usuario { get; set; }
    }
}
