//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadrigalDev_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_login
    {
        public int IdLogin { get; set; }
        public int UsuarioT { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }
    
        public virtual t_usuario t_usuario { get; set; }
    }
}
