//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadrigalDev_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_usuario
    {
        public t_usuario()
        {
            this.t_login = new HashSet<t_login>();
        }
    
        public int IdUsuario { get; set; }
        public int EmpresaT { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
    
        public virtual t_empresa t_empresa { get; set; }
        public virtual ICollection<t_login> t_login { get; set; }
    }
}
